//! ダッシュボード（管理UI向けAPI・静的アセット・WebSocket）のルート

use super::OPENAI_BODY_LIMIT_BYTES;
use crate::api::{audit_log, benchmarks, catalog, dashboard, dashboard_ws, logs, openai};
use crate::AppState;
use axum::{
    body::Body,
    extract::DefaultBodyLimit,
    extract::Path as AxumPath,
    http::{header, StatusCode},
    middleware,
    response::{IntoResponse, Response},
    routing::{get, post},
    Router,
};
use include_dir::{include_dir, Dir, File};
use mime_guess::MimeGuess;

static DASHBOARD_ASSETS: Dir = include_dir!("$CARGO_MANIFEST_DIR/src/web/static");
pub(super) const DASHBOARD_INDEX: &str = "index.html";
// NOTE: Playground機能は廃止され、ダッシュボード内のエンドポイント別Playgroundに移行
// const PLAYGROUND_INDEX: &str = "playground.html";
// Force rebuild when embedded dashboard/playground assets change.
// The file is generated by `llmlb/build.rs`.
const _DASHBOARD_ASSETS_BUILD_STAMP: &str = include_str!(concat!(
    env!("OUT_DIR"),
    "/dashboard_assets_build_stamp.txt"
));

/// `/api` 配下のダッシュボードAPIルート
pub(super) fn api_routes(state: &AppState) -> Router<AppState> {
    // ダッシュボードAPI（管理UI向け。JWTのみ）
    let dashboard_general_routes = Router::new()
        .route("/dashboard/endpoints", get(dashboard::get_endpoints))
        .route("/dashboard/models", get(dashboard::get_models))
        .route("/dashboard/playground/models", get(openai::list_models))
        .route("/dashboard/stats", get(dashboard::get_stats))
        .route(
            "/dashboard/request-history",
            get(dashboard::get_request_history),
        )
        .route("/dashboard/overview", get(dashboard::get_overview))
        .route(
            "/dashboard/metrics/{endpoint_id}",
            get(dashboard::get_node_metrics),
        )
        .route(
            "/dashboard/request-responses",
            get(dashboard::list_request_responses),
        )
        .route(
            "/dashboard/request-responses/{id}",
            get(dashboard::get_request_response_detail),
        )
        .route(
            "/dashboard/request-responses/export",
            get(dashboard::export_request_responses),
        )
        // トークン統計API
        .route("/dashboard/stats/tokens", get(dashboard::get_token_stats))
        .route(
            "/dashboard/stats/tokens/daily",
            get(dashboard::get_daily_token_stats),
        )
        .route(
            "/dashboard/stats/tokens/monthly",
            get(dashboard::get_monthly_token_stats),
        )
        .route("/dashboard/logs/lb", get(logs::get_lb_logs))
        // モデル別リクエスト統計（全エンドポイント横断）
        .route(
            "/dashboard/model-stats",
            get(dashboard::get_all_model_stats),
        )
        // SPEC-62ac4b68: Clients分析API
        .route("/benchmarks/tps", post(benchmarks::start_tps_benchmark))
        .route(
            "/benchmarks/tps/{run_id}",
            get(benchmarks::get_tps_benchmark),
        )
        .route("/dashboard/clients", get(dashboard::get_client_rankings))
        .route(
            "/dashboard/clients/timeline",
            get(dashboard::get_client_timeline),
        )
        .route(
            "/dashboard/clients/models",
            get(dashboard::get_client_models),
        )
        .route(
            "/dashboard/clients/heatmap",
            get(dashboard::get_client_heatmap),
        )
        .route(
            "/dashboard/clients/{ip}/detail",
            get(dashboard::get_client_detail),
        )
        .route(
            "/dashboard/clients/{ip}/api-keys",
            get(dashboard::get_client_api_keys),
        )
        // SPEC-62ac4b68: 設定API（閾値設定等）
        .route(
            "/dashboard/settings/{key}",
            get(dashboard::get_setting).put(dashboard::update_setting),
        )
        // カタログ検索API（HuggingFaceラッパー）
        .route("/catalog/search", get(catalog::search_catalog))
        .route(
            "/catalog/recommend-endpoints/{*repo_id}",
            get(catalog::recommend_endpoints),
        )
        .route("/catalog/{*repo_id}", get(catalog::get_catalog_model));

    let dashboard_playground_routes = Router::new()
        .route(
            "/dashboard/playground/chat/completions",
            post(openai::dashboard_playground_chat_completions),
        )
        .layer(DefaultBodyLimit::max(OPENAI_BODY_LIMIT_BYTES))
        .layer(middleware::from_fn(
            crate::auth::middleware::require_password_changed_middleware,
        ))
        .layer(middleware::from_fn(
            crate::auth::middleware::csrf_protect_middleware,
        ))
        .layer(middleware::from_fn_with_state(
            state.clone(),
            crate::auth::middleware::require_jwt_auth_middleware,
        ))
        .layer(middleware::from_fn_with_state(
            state.lifecycle.inference_gate.clone(),
            crate::inference_gate::inference_gate_middleware,
        ));

    // Load Test 専用エンドポイント: Chat と同じハンドラを再利用しつつ admin ロール限定。
    // Load Test は LB 経由で実推論を大量発行する運用ツールのため、viewer からの過負荷を防ぐ。
    // ミドルウェア順は dashboard_audit_routes を踏襲（jwt_auth で Claims を設定 → admin_role で判定）。
    let dashboard_playground_loadtest_routes = Router::new()
        .route(
            "/dashboard/playground/load-test/chat/completions",
            post(openai::dashboard_playground_chat_completions),
        )
        .layer(DefaultBodyLimit::max(OPENAI_BODY_LIMIT_BYTES))
        .layer(middleware::from_fn(
            crate::auth::middleware::require_password_changed_middleware,
        ))
        .layer(middleware::from_fn(
            crate::auth::middleware::csrf_protect_middleware,
        ))
        .layer(middleware::from_fn(
            crate::auth::middleware::require_admin_role_middleware,
        ))
        .layer(middleware::from_fn_with_state(
            state.clone(),
            crate::auth::middleware::require_jwt_auth_middleware,
        ))
        .layer(middleware::from_fn_with_state(
            state.lifecycle.inference_gate.clone(),
            crate::inference_gate::inference_gate_middleware,
        ));

    // 監査ログAPI (SPEC-8301d106): adminロールのみ
    let dashboard_audit_routes = Router::new()
        .route("/dashboard/audit-logs", get(audit_log::list_audit_logs))
        .route(
            "/dashboard/audit-logs/stats",
            get(audit_log::get_audit_log_stats),
        )
        .route(
            "/dashboard/audit-logs/verify",
            post(audit_log::verify_hash_chain),
        );

    {
        let dashboard_general_routes = dashboard_general_routes
            .layer(middleware::from_fn(
                crate::auth::middleware::require_password_changed_middleware,
            ))
            // 状態変更系（PUT /dashboard/settings 等）を他の mutation ルートと同様に
            // Cookie 認証時の CSRF から保護する（ヘッダ認証はミドルウェア側で対象外）
            .layer(middleware::from_fn(
                crate::auth::middleware::csrf_protect_middleware,
            ))
            .layer(middleware::from_fn_with_state(
                state.clone(),
                crate::auth::middleware::require_jwt_auth_middleware,
            ));
        let dashboard_audit_routes = dashboard_audit_routes
            .layer(middleware::from_fn(
                crate::auth::middleware::require_password_changed_middleware,
            ))
            .layer(middleware::from_fn(
                crate::auth::middleware::require_admin_role_middleware,
            ))
            .layer(middleware::from_fn_with_state(
                state.clone(),
                crate::auth::middleware::require_jwt_auth_middleware,
            ));
        dashboard_general_routes
            .merge(dashboard_audit_routes)
            .merge(dashboard_playground_routes)
            .merge(dashboard_playground_loadtest_routes)
    }
}

/// 管理UIの静的アセットとWebSocketのルート（ルート直下）
pub(super) fn ui_routes() -> Router<AppState> {
    let dashboard_routes = Router::new()
        .route("/dashboard", get(serve_dashboard_index))
        .route("/dashboard/", get(serve_dashboard_index))
        .route("/dashboard/{*path}", get(serve_dashboard_asset));

    let ws_routes = Router::new().route("/ws/dashboard", get(dashboard_ws::dashboard_ws_handler));

    dashboard_routes.merge(ws_routes)
}

async fn serve_dashboard_index() -> Response {
    embedded_dashboard_response(DASHBOARD_INDEX)
}

async fn serve_dashboard_asset(AxumPath(request_path): AxumPath<String>) -> Response {
    let normalized = normalize_dashboard_path(&request_path);
    match normalized {
        Some(path) => embedded_dashboard_response(&path),
        None => StatusCode::NOT_FOUND.into_response(),
    }
}

fn embedded_dashboard_response(path: &str) -> Response {
    match DASHBOARD_ASSETS.get_file(path) {
        Some(file) => file_response(file),
        None => StatusCode::NOT_FOUND.into_response(),
    }
}

fn file_response(file: &File<'_>) -> Response {
    let mime = MimeGuess::from_path(file.path())
        .first_or_octet_stream()
        .to_string();
    Response::builder()
        .status(StatusCode::OK)
        .header(header::CONTENT_TYPE, mime)
        .body(Body::from(file.contents().to_vec()))
        .expect("failed to build embedded dashboard response")
}

pub(super) fn normalize_dashboard_path(request_path: &str) -> Option<String> {
    let trimmed = request_path.trim_matches('/');
    if trimmed.is_empty() {
        return Some(DASHBOARD_INDEX.to_string());
    }
    if trimmed.contains("..") || trimmed.contains('\\') {
        return None;
    }
    Some(trimmed.to_string())
}
