//! REST APIハンドラー
//!
//! ノード登録、ヘルスチェック、プロキシAPI

pub mod api_keys;
pub mod audio;
pub mod auth;
pub mod cloud_models;
pub mod dashboard;
pub mod dashboard_ws;
/// エンドポイント管理API
pub mod endpoints;
/// APIエラーレスポンス型
pub mod error;
pub mod health;
pub mod images;
pub mod invitations;
pub mod logs;
/// モデル名のパース（量子化サフィックス対応）
pub mod model_name;
pub mod models;
pub mod openai;
pub mod proxy;
/// Open Responses API (SPEC-24157000)
pub mod responses;
pub mod users;

use crate::cloud_metrics;
use crate::common::auth::ApiKeyScope;
use crate::AppState;
use axum::{
    body::Body,
    extract::Path as AxumPath,
    http::{header, StatusCode},
    middleware,
    response::{IntoResponse, Response},
    routing::{delete, get, post, put},
    Router,
};
use include_dir::{include_dir, Dir, File};
use mime_guess::MimeGuess;

static DASHBOARD_ASSETS: Dir = include_dir!("$CARGO_MANIFEST_DIR/src/web/static");
const DASHBOARD_INDEX: &str = "index.html";
// NOTE: Playground機能は廃止され、ダッシュボード内のエンドポイント別Playgroundに移行
// const PLAYGROUND_INDEX: &str = "playground.html";
// Force rebuild when embedded dashboard/playground assets change.
// The file is generated by `llmlb/build.rs`.
const _DASHBOARD_ASSETS_BUILD_STAMP: &str = include_str!(concat!(
    env!("OUT_DIR"),
    "/dashboard_assets_build_stamp.txt"
));

/// APIllmlbを作成
#[allow(deprecated)] // NodeRegistry migration in progress - legacy APIs still registered
pub fn create_app(state: AppState) -> Router {
    let auth_disabled = crate::config::is_auth_disabled();

    // `/v0/*`: llmlb独自API（管理/運用向け）
    // JWTが必要な認証ルート（ログイン以外）
    let auth_routes = Router::new()
        .route("/auth/me", get(auth::me))
        .route("/auth/logout", post(auth::logout));

    let auth_routes = if auth_disabled {
        auth_routes.layer(middleware::from_fn(
            crate::auth::middleware::inject_dummy_admin_claims,
        ))
    } else {
        auth_routes.layer(middleware::from_fn_with_state(
            state.jwt_secret.clone(),
            crate::auth::middleware::jwt_auth_middleware,
        ))
    };

    // 管理者API（JWTまたはadminスコープAPIキー）
    let admin_routes = Router::new()
        .route("/users", get(users::list_users).post(users::create_user))
        .route(
            "/users/:id",
            put(users::update_user).delete(users::delete_user),
        )
        .route(
            "/api-keys",
            get(api_keys::list_api_keys).post(api_keys::create_api_key),
        )
        .route(
            "/api-keys/:id",
            put(api_keys::update_api_key).delete(api_keys::delete_api_key),
        )
        .route(
            "/invitations",
            get(invitations::list_invitations).post(invitations::create_invitation),
        )
        .route("/invitations/:id", delete(invitations::revoke_invitation))
        // ダッシュボードAPI
        // NOTE: /dashboard/nodes は廃止済み、/dashboard/endpoints を使用
        .route(
            "/dashboard/nodes",
            get({
                #[allow(deprecated)]
                dashboard::get_nodes
            }),
        )
        .route("/dashboard/endpoints", get(dashboard::get_endpoints))
        .route("/dashboard/stats", get(dashboard::get_stats))
        .route(
            "/dashboard/request-history",
            get(dashboard::get_request_history),
        )
        .route("/dashboard/overview", get(dashboard::get_overview))
        .route(
            "/dashboard/metrics/:node_id",
            get(dashboard::get_node_metrics),
        )
        .route(
            "/dashboard/request-responses",
            get(dashboard::list_request_responses),
        )
        .route(
            "/dashboard/request-responses/:id",
            get(dashboard::get_request_response_detail),
        )
        .route(
            "/dashboard/request-responses/export",
            get(dashboard::export_request_responses),
        )
        // トークン統計API
        .route("/dashboard/stats/tokens", get(dashboard::get_token_stats))
        .route(
            "/dashboard/stats/tokens/daily",
            get(dashboard::get_daily_token_stats),
        )
        .route(
            "/dashboard/stats/tokens/monthly",
            get(dashboard::get_monthly_token_stats),
        )
        .route("/dashboard/logs/lb", get(logs::get_lb_logs))
        // ノードログ取得（lb→node proxy）
        .route("/nodes/:node_id/logs", get(logs::get_node_logs))
        // モデル管理API (Admin のみ: register/delete)
        .route("/models/register", post(models::register_model))
        .route("/models/*model_name", delete(models::delete_model))
        // Prometheus metrics（cloud prefix含む独自メトリクス）
        .route("/metrics/cloud", get(cloud_metrics::export_metrics));

    let admin_routes = if auth_disabled {
        admin_routes.layer(middleware::from_fn(
            crate::auth::middleware::inject_dummy_admin_claims,
        ))
    } else {
        admin_routes.layer(middleware::from_fn_with_state(
            state.clone(),
            crate::auth::middleware::admin_or_api_key_middleware,
        ))
    };

    // エンドポイント管理API（SPEC-66555000）
    // すべてのエンドポイントルートを単一のRouterに統合
    // 書き込み操作はハンドラー内でensure_adminで権限チェック
    let endpoint_routes = Router::new()
        .route(
            "/endpoints",
            get(endpoints::list_endpoints).post(endpoints::create_endpoint),
        )
        .route(
            "/endpoints/:id",
            get(endpoints::get_endpoint)
                .put(endpoints::update_endpoint)
                .delete(endpoints::delete_endpoint),
        )
        .route("/endpoints/:id/test", post(endpoints::test_endpoint))
        .route("/endpoints/:id/sync", post(endpoints::sync_endpoint_models))
        .route(
            "/endpoints/:id/models",
            get(endpoints::list_endpoint_models),
        )
        // SPEC-66555000: ダウンロードAPI
        .route("/endpoints/:id/download", post(endpoints::download_model))
        .route(
            "/endpoints/:id/download/progress",
            get(endpoints::download_progress),
        )
        // SPEC-66555000: モデルメタデータAPI
        .route(
            "/endpoints/:id/models/:model/info",
            get(endpoints::get_model_info),
        );

    let endpoint_routes = if auth_disabled {
        endpoint_routes.layer(middleware::from_fn(
            crate::auth::middleware::inject_dummy_admin_claims,
        ))
    } else {
        endpoint_routes.layer(middleware::from_fn_with_state(
            state.clone(),
            crate::auth::middleware::authenticated_middleware,
        ))
    };

    // Playground用プロキシ（JWT認証のみ、APIキー不可）
    // ダッシュボードにログインしているユーザーのみがエンドポイントに直接リクエストを転送できる
    let playground_proxy_routes = Router::new().route(
        "/endpoints/:id/chat/completions",
        post(endpoints::proxy_chat_completions),
    );

    let playground_proxy_routes = if auth_disabled {
        playground_proxy_routes.layer(middleware::from_fn(
            crate::auth::middleware::inject_dummy_admin_claims,
        ))
    } else {
        playground_proxy_routes.layer(middleware::from_fn_with_state(
            state.jwt_secret.clone(),
            crate::auth::middleware::jwt_auth_middleware,
        ))
    };

    // モデル配布レジストリ（Runtimeスコープが必要）
    // SPEC-66555000: POST /v0/nodes（ノード自己登録）は廃止されました
    // 新しい実装は POST /v0/endpoints を使用してください
    let model_registry_routes = Router::new()
        // モデル配布レジストリ（複数ファイル: safetensors 等）
        .route(
            "/models/registry/:model_name/manifest.json",
            get(models::get_model_registry_manifest),
        );

    let model_registry_routes = if auth_disabled {
        model_registry_routes
    } else {
        model_registry_routes
            .layer(middleware::from_fn_with_state(
                ApiKeyScope::Endpoint,
                crate::auth::middleware::require_api_key_scope_middleware,
            ))
            .layer(middleware::from_fn_with_state(
                state.db_pool.clone(),
                crate::auth::middleware::api_key_auth_middleware,
            ))
    };

    // モデル一覧API (Admin OR Runtime スコープで利用可能)
    // /v0/models はランタイム同期用の登録済みモデル一覧
    // /v0/models/hub はダッシュボード向けの対応モデル一覧 + ステータス
    let models_list_routes = if auth_disabled {
        Router::new()
            .route("/models", get(models::list_models))
            .route("/models/hub", get(models::list_models_with_status))
    } else {
        Router::new()
            .route("/models", get(models::list_models))
            .route("/models/hub", get(models::list_models_with_status))
            .layer(middleware::from_fn_with_state(
                state.clone(),
                crate::auth::middleware::admin_or_runtime_middleware,
            ))
    };

    // SPEC-66555000: POST /v0/health（プッシュ型ヘルスチェック）は廃止されました
    // 新しいエンドポイントはプル型ヘルスチェック（EndpointHealthChecker）を使用

    // APIキー認証が必要なルート（OpenAI互換エンドポイント）
    let api_key_routes = Router::new()
        .route("/v1/chat/completions", post(openai::chat_completions))
        .route("/v1/completions", post(openai::completions))
        .route("/v1/embeddings", post(openai::embeddings))
        // Open Responses API（SPEC-24157000）
        .route("/v1/responses", post(responses::post_responses))
        // 音声API（OpenAI Audio API互換）
        .route("/v1/audio/transcriptions", post(audio::transcriptions))
        .route("/v1/audio/speech", post(audio::speech))
        // 画像API（OpenAI Images API互換）
        .route("/v1/images/generations", post(images::generations))
        .route("/v1/images/edits", post(images::edits))
        .route("/v1/images/variations", post(images::variations));

    let api_key_protected_routes = if auth_disabled {
        api_key_routes
    } else {
        api_key_routes
            .layer(middleware::from_fn_with_state(
                ApiKeyScope::Api,
                crate::auth::middleware::require_api_key_scope_middleware,
            ))
            .layer(middleware::from_fn_with_state(
                state.db_pool.clone(),
                crate::auth::middleware::api_key_auth_middleware,
            ))
    };

    // `/v1/models*` は外部クライアント(APIキー)からのみ参照される
    // SPEC-66555000: ノードトークン認証は廃止されました
    let models_routes = Router::new()
        .route("/v1/models", get(openai::list_models))
        .route("/v1/models/:model_id", get(openai::get_model));

    let models_protected_routes = if auth_disabled {
        models_routes
    } else {
        models_routes
            .layer(middleware::from_fn_with_state(
                ApiKeyScope::Api,
                crate::auth::middleware::require_api_key_scope_middleware,
            ))
            .layer(middleware::from_fn_with_state(
                state.db_pool.clone(),
                crate::auth::middleware::api_key_auth_middleware,
            ))
    };

    // NOTE: /v0/models (GET) は Admin/Node スコープ共用。
    // 外部クライアントは /v1/models を使用してください（Azure OpenAI 形式の capabilities 付き）。

    // SPEC-66555000: テスト用内部エンドポイント（デバッグビルドのみ）
    // NOTE: ノード登録ベースのテストは廃止。エンドポイント登録を使用
    let test_routes = Router::new();

    Router::new()
        // `/v0/*`: llmlb独自API（互換不要・versioned）
        .nest(
            "/v0",
            Router::new()
                // 認証エンドポイント（ログインは認証不要）
                .route("/auth/login", post(auth::login))
                .route("/auth/register", post(auth::register))
                .merge(auth_routes)
                .merge(admin_routes)
                .merge(endpoint_routes)
                .merge(playground_proxy_routes)
                .merge(model_registry_routes)
                .merge(models_list_routes)
                // デバッグ用テストエンドポイント
                .merge(test_routes),
        )
        // OpenAI互換API
        .merge(api_key_protected_routes)
        .merge(models_protected_routes)
        .route("/dashboard", get(serve_dashboard_index))
        .route("/dashboard/", get(serve_dashboard_index))
        .route("/dashboard/*path", get(serve_dashboard_asset))
        // NOTE: Playground機能は廃止され、ダッシュボード内のエンドポイント別Playgroundに移行
        // /playground/* ルートは削除済み
        // WebSocket endpoint for real-time dashboard updates
        .route("/ws/dashboard", get(dashboard_ws::dashboard_ws_handler))
        .fallback(|| async { StatusCode::NOT_FOUND })
        .with_state(state)
}

async fn serve_dashboard_index() -> Response {
    embedded_dashboard_response(DASHBOARD_INDEX)
}

async fn serve_dashboard_asset(AxumPath(request_path): AxumPath<String>) -> Response {
    let normalized = normalize_dashboard_path(&request_path);
    match normalized {
        Some(path) => embedded_dashboard_response(&path),
        None => StatusCode::NOT_FOUND.into_response(),
    }
}

fn embedded_dashboard_response(path: &str) -> Response {
    match DASHBOARD_ASSETS.get_file(path) {
        Some(file) => file_response(file),
        None => StatusCode::NOT_FOUND.into_response(),
    }
}

fn file_response(file: &File<'_>) -> Response {
    let mime = MimeGuess::from_path(file.path())
        .first_or_octet_stream()
        .to_string();
    Response::builder()
        .status(StatusCode::OK)
        .header(header::CONTENT_TYPE, mime)
        .body(Body::from(file.contents().to_vec()))
        .expect("failed to build embedded dashboard response")
}

fn normalize_dashboard_path(request_path: &str) -> Option<String> {
    let trimmed = request_path.trim_matches('/');
    if trimmed.is_empty() {
        return Some(DASHBOARD_INDEX.to_string());
    }
    if trimmed.contains("..") || trimmed.contains('\\') {
        return None;
    }
    Some(trimmed.to_string())
}

#[cfg(test)]
mod tests {
    //! NOTE: NodeRegistry廃止（SPEC-66555000）に伴い、EndpointRegistryベースに更新済み。
    //! NodeRegistry.register()を使用していたテストは#[ignore]でマーク。

    use super::*;
    use crate::balancer::LoadManager;
    use axum::body::{to_bytes, Body};
    use axum::http::{Request, StatusCode};
    use std::sync::Arc;
    use tower::Service;

    async fn test_state() -> AppState {
        let db_pool = sqlx::SqlitePool::connect("sqlite::memory:")
            .await
            .expect("Failed to create test database");
        sqlx::migrate!("./migrations")
            .run(&db_pool)
            .await
            .expect("Failed to run migrations");
        let endpoint_registry = crate::registry::endpoints::EndpointRegistry::new(db_pool.clone())
            .await
            .expect("Failed to create endpoint registry");
        let load_manager = LoadManager::new(Arc::new(endpoint_registry.clone()));
        let request_history = std::sync::Arc::new(
            crate::db::request_history::RequestHistoryStorage::new(db_pool.clone()),
        );
        let jwt_secret = "test-secret".to_string();
        AppState {
            load_manager,
            request_history,
            db_pool,
            jwt_secret,
            http_client: reqwest::Client::new(),
            queue_config: crate::config::QueueConfig::from_env(),
            event_bus: crate::events::create_shared_event_bus(),
            endpoint_registry,
        }
    }

    #[tokio::test]
    async fn test_dashboard_static_served() {
        let state = test_state().await;
        let mut app = create_app(state);
        let response = app
            .call(
                Request::builder()
                    .method(axum::http::Method::GET)
                    .uri("/dashboard/index.html")
                    .body(Body::empty())
                    .unwrap(),
            )
            .await
            .unwrap();

        let status = response.status();
        let (parts, body) = response.into_parts();
        let bytes = to_bytes(body, 1024 * 1024).await.unwrap();

        assert_eq!(status, StatusCode::OK);
        let content_type = parts.headers[axum::http::header::CONTENT_TYPE]
            .to_str()
            .unwrap();
        assert!(content_type.starts_with("text/html"));
        assert!(bytes.starts_with(b"<!DOCTYPE html"));
    }

    // NOTE: test_playground_static_served は廃止
    // Playground機能はダッシュボード内のエンドポイント別Playgroundに移行 (#playground/:endpointId)

    /// NodeRegistry廃止: EndpointRegistry経由のテストに移行が必要 (SPEC-66555000)
    #[tokio::test]
    #[ignore = "NodeRegistry廃止: EndpointRegistry経由のテストに移行が必要 (SPEC-66555000)"]
    async fn test_dashboard_nodes_endpoint_returns_json() {
        let state = test_state().await;
        let mut app = create_app(state);
        let response = app
            .call(
                Request::builder()
                    .method(axum::http::Method::GET)
                    .uri("/v0/dashboard/endpoints")
                    .header("x-api-key", "sk_debug")
                    .body(Body::empty())
                    .unwrap(),
            )
            .await
            .unwrap();

        assert_eq!(response.status(), StatusCode::OK);
    }

    /// NodeRegistry廃止: EndpointRegistry経由のテストに移行が必要 (SPEC-66555000)
    #[tokio::test]
    #[ignore = "NodeRegistry廃止: EndpointRegistry経由のテストに移行が必要 (SPEC-66555000)"]
    async fn test_dashboard_overview_endpoint_returns_all_sections() {
        let state = test_state().await;
        let mut app = create_app(state);
        let response = app
            .call(
                Request::builder()
                    .method(axum::http::Method::GET)
                    .uri("/v0/dashboard/overview")
                    .header("x-api-key", "sk_debug")
                    .body(Body::empty())
                    .unwrap(),
            )
            .await
            .unwrap();

        assert_eq!(response.status(), StatusCode::OK);
    }

    /// NodeRegistry廃止: EndpointRegistry経由のテストに移行が必要 (SPEC-66555000)
    #[tokio::test]
    #[ignore = "NodeRegistry廃止: EndpointRegistry経由のテストに移行が必要 (SPEC-66555000)"]
    async fn test_dashboard_metrics_endpoint_returns_history() {
        let state = test_state().await;
        let mut app = create_app(state);
        let response = app
            .call(
                Request::builder()
                    .method(axum::http::Method::GET)
                    .uri("/v0/dashboard/request-history")
                    .header("x-api-key", "sk_debug")
                    .body(Body::empty())
                    .unwrap(),
            )
            .await
            .unwrap();

        assert_eq!(response.status(), StatusCode::OK);
    }
}
